Feature/designator
bazo-blockchain/lazo pull request #55
Opened 2019-04-19 07:32 UTC by rpfister102

2019-04-19 07:35 UTC, rpfister102 commented on parser/parser_expression.go
> +	var left node.Node
Not possible... If I would merge thos two, left would be of type DesignatorNode but is later values of type DesignatorNode, ElementAccessNode and MemberAccessNode are assigned to it.

2019-04-19 11:46 UTC, tk-codes requested changes

2019-04-19 11:46 UTC, tk-codes commented on parser/node/nodes.go
> +	Designator Node
It is better to create DesignatorNode interface than using the Node interface.

2019-04-19 11:46 UTC, tk-codes commented on parser/parser.go
> +		AbstractNode: p.newAbstractNode(),
Assignment's position should be the position of designator

2019-04-19 11:46 UTC, tk-codes commented on parser/parser_expression_test.go
> +	assertHasError(t, p)
Use `assertErrorAt` for checking errors

2019-04-21 11:03 UTC, tk-codes commented on parser/parser_expression.go
> +	var left node.Node
@rpfister102 Could be resolved like this https://github.com/bazo-blockchain/lazo/pull/55/commits/6b69b36e48cde169f015198f7321ed9ea519d08c

2019-04-21 12:01 UTC, tk-codes commented on parser/parser.go
> +		AbstractNode: p.newAbstractNode(),
Fixed https://github.com/bazo-blockchain/lazo/pull/55/commits/695f45cfe8798a3abf2696edbdb9dcaa87988c35

2019-04-21 12:33 UTC, tk-codes commented on parser/parser_expression_test.go
> +	assertHasError(t, p)
Fixed https://github.com/bazo-blockchain/lazo/pull/55/commits/50bbce4be94f797c8c6332a68f58e75a84466e61

2019-04-21 12:38 UTC, tk-codes approved these changes
@rpfister102 I fixed the requested changes on my own in order to continue with other features

2019-04-21 12:39 UTC, merged