Check Expression and Shorthand Assignments
bazo-blockchain/lazo pull request #77
Opened 2019-05-16 17:59 UTC by tk-codes

Checks https://github.com/bazo-blockchain/lazo/issues/70

2019-05-17 06:04 UTC, skas102 requested changes

2019-05-17 06:04 UTC, rpfister102 commented on checker/typecheck/type_check_visitor.go
> +			v.reportError(node, "Arithmetic operators can only be applied to int types")
Die Message stimmt nicht ganz, für string geht es ja auch.
Eine einfache Lösung wäre es, zu prüfen ob die Werte vom Typen int oder string sind, falls nicht gleich eine message spezifisch für + zurückgeben.

2019-05-18 11:25 UTC, tk-codes commented on checker/typecheck/type_check_visitor.go
> +			v.reportError(node, "Arithmetic operators can only be applied to int types")
Fixed https://github.com/bazo-blockchain/lazo/pull/77/commits/6d1023fcd869b403f8b8b2d1ee41d2b288fdbc15

2019-05-18 11:47 UTC, skas102 approved these changes

2019-05-18 11:47 UTC, merged