Generate map opcodes
bazo-blockchain/lazo pull request #79
Opened 2019-05-19 20:29 UTC by tk-codes

Resolves https://github.com/bazo-blockchain/lazo/issues/44

2019-05-19 20:35 UTC, tk-codes commented on generator/emit/il_code_generation_visitor.go
> +func (v *ILCodeGenerationVisitor) isVariableDecl(decl symbol.Symbol) bool {
Fixed https://github.com/bazo-blockchain/lazo/pull/79/commits/1b9d085b84ab92328b2c42485b02156d9254b9d3

2019-05-20 08:03 UTC, skas102 requested changes

2019-05-20 08:03 UTC, skas102 commented on generator/emit/il_code_generation_visitor.go
> +		// Workaround for single dereference
This comment is really unclear. if you do comments in code, please make sure they are also understandable for people not yet involved in the project.

2019-05-20 08:03 UTC, skas102 commented on generator/emit/il_code_generation_visitor.go
> +			// Workaround for single dereference
Same here

2019-05-22 09:08 UTC, tk-codes commented on generator/emit/il_code_generation_visitor.go
> +		// Workaround for single dereference
Updated in https://github.com/bazo-blockchain/lazo/pull/79/commits/c3de44b8aeb11479143be88a9953060dd9b90159

2019-05-22 09:08 UTC, tk-codes commented on generator/emit/il_code_generation_visitor.go
> +			// Workaround for single dereference
Updated in https://github.com/bazo-blockchain/lazo/pull/79/commits/c3de44b8aeb11479143be88a9953060dd9b90159

2019-05-22 11:29 UTC, merged